const repdbPair = (slug, startLabel = "起始", peakLabel = "收缩") => ({
  kind: "pair",
  source: "repdb",
  frames: [
    { src: `./assets/exercises/${slug}-start.webp`, label: startLabel },
    { src: `./assets/exercises/${slug}-peak.webp`, label: peakLabel },
  ],
});

const singleVisual = (src, label, source = "repdb") => ({
  kind: "single",
  source,
  frames: [{ src, label }],
});

const GUIDE_BASE = {
  "leg-press": {
    visual: repdbPair("leg-press", "下放", "推起"),
    muscleMap: "./assets/muscles/quads-glutes.svg",
    primary: ["股四头肌", "臀大肌"],
    secondary: ["大腿后侧", "内收肌"],
    steps: [
      "调整靠背，让臀部和下背稳定贴住靠垫。",
      "双脚与肩同宽踩稳踏板，膝盖朝脚尖方向弯曲。",
      "下放到腰背仍能贴稳的位置，再用全脚掌推起。",
    ],
    cues: ["膝盖始终跟随脚尖", "脚跟不要离开踏板", "顶端保留一点膝屈"],
    mistakes: ["膝盖向内扣", "下放过深导致骨盆卷起", "推到顶时锁死膝盖"],
    breathing: "下放吸气，推起时呼气。",
  },
  "chest-press": {
    visual: repdbPair("chest-press-machine", "打开", "推合"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌"],
    secondary: ["肱三头肌", "三角肌前束"],
    steps: [
      "调座椅至握把大致与胸中部齐平，头背贴稳。",
      "肩胛轻轻向后下方收住，手腕保持中立。",
      "向前推至手臂接近伸直，再受控回到胸部拉伸位。",
    ],
    cues: ["胸口保持打开", "肩膀远离耳朵", "肘部不要抬得过高"],
    mistakes: ["推起时耸肩", "手腕折弯", "回程过快让配重撞击"],
    breathing: "回程吸气，推起时呼气。",
  },
  "lat-pulldown": {
    visual: repdbPair("lat-pulldown", "伸展", "下拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["肱二头肌", "菱形肌", "斜方肌下部"],
    steps: [
      "大腿固定在压垫下，握距略宽于肩。",
      "先把肩胛向下沉，再让肘部向身体两侧下拉。",
      "拉到上胸附近，停顿后慢慢还原至背部充分伸展。",
    ],
    cues: ["想象肘部向口袋移动", "胸口微抬", "身体只需轻微后倾"],
    mistakes: ["先用手臂猛拽", "身体大幅后仰", "把横杆拉到颈后"],
    breathing: "还原吸气，下拉时呼气。",
  },
  "leg-curl": {
    visual: repdbPair("seated-leg-curl", "伸展", "屈膝"),
    muscleMap: "./assets/muscles/hamstrings.svg",
    primary: ["腘绳肌"],
    secondary: ["腓肠肌"],
    steps: [
      "让器械转轴与膝关节大致对齐，压垫固定大腿。",
      "脚踝垫放在小腿下端，臀部和腰背贴稳。",
      "用大腿后侧把脚跟向下后方卷，停顿后慢放。",
    ],
    cues: ["大腿不要离开坐垫", "顶峰夹紧一秒", "回程保持控制"],
    mistakes: ["臀部抬起", "用惯性甩动", "回程直接松掉配重"],
    breathing: "伸膝吸气，屈膝发力时呼气。",
  },
  "seated-row": {
    visual: repdbPair("wide-grip-seated-cable-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌", "菱形肌"],
    secondary: ["三角肌后束", "肱二头肌"],
    steps: [
      "坐稳并保持脊柱自然，手臂前伸让背部得到拉伸。",
      "先收肩胛，再把肘部沿身体两侧向后拉。",
      "把手靠近腹部后停一下，缓慢送回。",
    ],
    cues: ["胸口朝前", "肘部向后而不是手向后", "肩膀保持下沉"],
    mistakes: ["反复前后甩动身体", "耸肩拉动", "只弯手肘没有收背"],
    breathing: "前伸吸气，后拉时呼气。",
  },
  "lateral-raise": {
    visual: repdbPair("lateral-raise", "垂臂", "抬臂"),
    muscleMap: "./assets/muscles/side-delts.svg",
    primary: ["三角肌中束"],
    secondary: ["冈上肌", "斜方肌"],
    steps: [
      "站稳，手肘微弯，哑铃放在身体两侧。",
      "让手肘带动手臂向侧上方抬起。",
      "抬到接近肩高后停顿，再慢慢下放。",
    ],
    cues: ["重量宁轻不甩", "手肘略高于手腕", "肩膀远离耳朵"],
    mistakes: ["借腰腿摆动", "耸肩代偿", "抬得过高并内旋手臂"],
    breathing: "下放吸气，抬起时呼气。",
  },
  "machine-lateral-raise": {
    visual: repdbPair("seated-dumbbell-lateral-raise", "垂臂", "抬臂"),
    muscleMap: "./assets/muscles/side-delts.svg",
    primary: ["三角肌中束"],
    secondary: ["冈上肌", "斜方肌"],
    steps: [
      "调座椅让器械转轴接近肩关节，背部贴稳。",
      "手肘或前臂贴住垫子，用手肘向外上方带动。",
      "抬至接近肩高，短暂停顿后受控下放。",
    ],
    cues: ["手臂只是杠杆", "肩膀不要耸起", "全程保持同一轨迹"],
    mistakes: ["用身体弹起重量", "座椅过高或过低", "下放时配重直接落到底"],
    breathing: "下放吸气，抬起时呼气。",
  },
  "reverse-fly": {
    visual: repdbPair("dumbbell-reverse-fly", "合拢", "展开"),
    muscleMap: "./assets/muscles/rear-delts.svg",
    primary: ["三角肌后束"],
    secondary: ["菱形肌", "斜方肌中部"],
    steps: [
      "俯身或贴稳胸垫，脊柱保持自然，手肘微弯。",
      "手臂向两侧展开，想象用手肘带动。",
      "肩后侧收紧后停一下，再慢慢回到起始位。",
    ],
    cues: ["肩膀保持下沉", "手肘轨迹略低于肩", "用小重量找后束"],
    mistakes: ["耸肩夹背过多", "甩动躯干", "手臂伸得过直并锁肘"],
    breathing: "合拢吸气，展开时呼气。",
  },
  "triceps-pushdown": {
    visual: repdbPair("tricep-pushdown", "屈肘", "下压"),
    muscleMap: "./assets/muscles/triceps.svg",
    primary: ["肱三头肌"],
    secondary: ["前臂肌群"],
    steps: [
      "站稳并略微前倾，把肘部固定在身体两侧。",
      "向下伸直手肘，绳索动作可在底端稍向两边分开。",
      "肱三头肌收紧后，缓慢回到前臂接近水平的位置。",
    ],
    cues: ["只让前臂转动", "手腕保持中立", "底端完全收紧但不甩"],
    mistakes: ["肘部前后飘动", "用身体重量下压", "回程过高让肩部接管"],
    breathing: "回程吸气，下压时呼气。",
  },
  "biceps-curl": {
    visual: repdbPair("bicep-curl", "伸肘", "弯举"),
    muscleMap: "./assets/muscles/biceps.svg",
    primary: ["肱二头肌"],
    secondary: ["肱肌", "肱桡肌"],
    steps: [
      "站稳并收紧核心，肘部放在身体两侧。",
      "保持上臂稳定，把重量弯举到二头肌充分收紧。",
      "慢慢伸肘回到起始位，不要直接掉下去。",
    ],
    cues: ["肘部像钉在身侧", "顶峰不抬肩", "下放比举起更慢"],
    mistakes: ["甩腰借力", "肘部向前跑", "动作只做一半"],
    breathing: "下放吸气，弯举时呼气。",
  },
  crunch: {
    visual: repdbPair("crunches", "伸展", "卷起"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹直肌"],
    secondary: ["腹斜肌"],
    steps: [
      "仰卧屈膝，腰背自然贴近垫面，手轻放头侧或胸前。",
      "先收紧腹部，再把肩胛骨卷离地面。",
      "停顿后逐节慢慢回落，不需要坐起。",
    ],
    cues: ["肋骨向骨盆靠近", "下巴与胸口留一拳", "动作幅度小而稳定"],
    mistakes: ["双手拉脖子", "用髋屈肌直接坐起", "憋气猛卷"],
    breathing: "下放吸气，卷起时缓慢呼气。",
  },
  plank: {
    visual: singleVisual("./assets/exercises/plank-main.webp", "稳定支撑"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹横肌", "腹直肌"],
    secondary: ["臀肌", "肩部稳定肌"],
    steps: [
      "肘部放在肩膀正下方，前臂压稳地面。",
      "伸直双腿，收紧腹部和臀部，让身体成一条直线。",
      "保持自然呼吸，在姿势开始变形前结束。",
    ],
    cues: ["尾骨微收", "肋骨不要外翻", "用肘部推开地面"],
    mistakes: ["塌腰或撅臀", "低头憋气", "为了时长牺牲姿势"],
    breathing: "保持均匀呼吸，每次呼气时轻收腹部。",
  },
  "hack-squat": {
    visual: repdbPair("hack-squat", "下蹲", "站起"),
    muscleMap: "./assets/muscles/quads-glutes.svg",
    primary: ["股四头肌", "臀大肌"],
    secondary: ["内收肌", "腘绳肌"],
    steps: [
      "肩背贴稳靠垫，双脚与肩同宽踩在踏板上。",
      "解锁后屈膝下蹲，膝盖沿脚尖方向移动。",
      "下到腰背仍稳定的位置，用全脚掌发力站起。",
    ],
    cues: ["脚掌三点压稳", "膝盖不内扣", "臀背始终贴垫"],
    mistakes: ["脚跟抬起", "底部骨盆卷起", "顶端猛锁膝盖"],
    breathing: "下蹲吸气，站起时呼气。",
  },
  "incline-press": {
    visual: repdbPair("smith-machine-incline-bench-press", "下放", "推起"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌上部"],
    secondary: ["三角肌前束", "肱三头肌"],
    steps: [
      "调好座椅或靠背，让推举轨迹落在上胸位置。",
      "肩胛向后下方固定，双脚踩稳，手腕保持中立。",
      "受控下放到舒适深度，再向上推至接近伸直。",
    ],
    cues: ["胸口微抬", "前臂尽量垂直", "肩膀不要向前顶"],
    mistakes: ["角度过高变成肩推", "肘部张到正侧方", "腰部过度拱起"],
    breathing: "下放吸气，推起时呼气。",
  },
  "chest-supported-row": {
    visual: repdbPair("chest-supported-db-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌", "菱形肌"],
    secondary: ["三角肌后束", "肱二头肌"],
    steps: [
      "胸口贴稳支撑垫，双脚固定，手臂自然前伸。",
      "先收肩胛，再让肘部向后拉过身体。",
      "背部收紧后停顿，缓慢伸臂回到完整拉伸。",
    ],
    cues: ["胸不离垫", "肩膀保持下沉", "肘部决定拉向位置"],
    mistakes: ["抬胸离开支撑", "耸肩拉动", "用手腕向上勾重量"],
    breathing: "前伸吸气，后拉时呼气。",
  },
  "hip-thrust": {
    visual: repdbPair("hip-thrust", "下放", "顶髋"),
    muscleMap: "./assets/muscles/glutes.svg",
    primary: ["臀大肌"],
    secondary: ["腘绳肌", "内收肌"],
    steps: [
      "让上背稳定靠住支撑，双脚踩稳，顶端小腿接近垂直。",
      "收紧腹部并保持下巴微收，用臀部把髋推起。",
      "顶端让躯干与大腿接近一线，夹臀后慢慢下放。",
    ],
    cues: ["肋骨收住", "脚跟发力", "顶端夹臀而不是仰腰"],
    mistakes: ["用腰椎过伸顶起", "脚离身体太远或太近", "头部后仰"],
    breathing: "下放吸气，顶髋时呼气。",
  },
  "neutral-pulldown": {
    visual: repdbPair("v-bar-lat-pulldown", "伸展", "下拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["肱二头肌", "菱形肌"],
    steps: [
      "用中立握把坐稳，大腿固定，胸口微抬。",
      "先让肩胛下沉，再把肘部朝身体两侧向下拉。",
      "握把靠近上胸后停顿，受控回到手臂伸展位。",
    ],
    cues: ["肘向下走", "手只是挂钩", "躯干保持稳定"],
    mistakes: ["用手臂先发力", "大幅后仰借力", "回程耸肩失控"],
    breathing: "还原吸气，下拉时呼气。",
  },
  "hip-abduction": {
    visual: repdbPair("hip-abduction", "合拢", "外展"),
    muscleMap: "./assets/muscles/hip-abductors.svg",
    primary: ["臀中肌", "臀小肌"],
    secondary: ["阔筋膜张肌"],
    steps: [
      "坐稳并让背部贴住靠垫，双脚放稳。",
      "保持骨盆不动，用臀部把双腿向外打开。",
      "外展到可控范围后停一下，再缓慢合拢。",
    ],
    cues: ["髋部发力", "膝盖匀速打开", "回程仍保持张力"],
    mistakes: ["身体前后摆动", "靠弹力快速开合", "配重回落时完全放松"],
    breathing: "合拢吸气，外展时呼气。",
  },
  "calf-raise": {
    visual: repdbPair("machine-calf-raise", "下沉", "提踵"),
    muscleMap: "./assets/muscles/calves.svg",
    primary: ["腓肠肌", "比目鱼肌"],
    secondary: ["足底稳定肌"],
    steps: [
      "前脚掌踩稳踏台，脚跟悬空，膝盖保持自然。",
      "先让脚跟缓慢下沉，感受小腿完整拉伸。",
      "用前脚掌推起脚跟，顶端停一下后慢慢下放。",
    ],
    cues: ["脚踝直上直下", "顶端充分收紧", "底部停顿不要弹"],
    mistakes: ["动作幅度过小", "脚踝向内外翻", "借膝盖弹动"],
    breathing: "下沉吸气，提踵时呼气。",
  },
  "core-choice": {
    visual: repdbPair("crunches", "伸展", "卷起"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹直肌", "腹横肌"],
    secondary: ["腹斜肌", "髋部稳定肌"],
    steps: [
      "从卷腹、死虫或平板支撑中选一个当天最稳的动作。",
      "先收紧腹部并固定骨盆，再开始四肢动作。",
      "腰背失去控制时立即结束这一组。",
    ],
    cues: ["肋骨和骨盆保持对齐", "动作慢且可控", "质量优先于次数"],
    mistakes: ["腰部拱起或塌下", "屏住呼吸", "只追次数忽略稳定"],
    breathing: "保持连续呼吸，最费力阶段缓慢呼气。",
  },
  cardio: {
    visual: {
      kind: "pair",
      source: "mixed",
      frames: [
        { src: "./assets/exercises/walking-treadmill-start.jpg", label: "稳定步态" },
        { src: "./assets/exercises/air-bike-main.webp", label: "单车选项" },
      ],
    },
    muscleMap: "./assets/muscles/cardio-lower.svg",
    primary: ["股四头肌", "臀肌", "小腿"],
    secondary: ["腘绳肌", "心肺系统"],
    steps: [
      "力量训练后先用低强度进入节奏，再逐步调到目标坡度或阻力。",
      "保持能说短句的中等强度，步幅和踩踏节奏稳定。",
      "最后两分钟降低强度，让呼吸慢慢恢复。",
    ],
    cues: ["扶手只用于保持平衡", "身体不要趴在机器上", "腿很累就主动降强度"],
    mistakes: ["一开始就把强度拉满", "紧抓扶手抵消坡度", "腿部主训练后仍硬撑高坡"],
    breathing: "保持连续、规律的呼吸，不要憋气。",
  },
  "easy-swim": {
    visual: singleVisual("./assets/exercises/breaststroke.gif", "蛙泳动作循环", "wikimedia"),
    muscleMap: "./assets/muscles/swim-full.svg",
    primary: ["背阔肌", "胸肌", "大腿内侧"],
    secondary: ["肩部", "臀腿", "核心"],
    steps: [
      "双臂前伸滑行，随后向外抱水并抬头换气。",
      "手臂前伸时收腿，脚跟靠近臀部。",
      "脚掌外翻后向后蹬夹，身体重新伸直滑行。",
    ],
    cues: ["先抱水再换气", "蹬夹后留出滑行", "以轻松恢复为主"],
    mistakes: ["抬头过高导致腰背紧张", "只蹬不夹", "全程抢节奏没有滑行"],
    breathing: "抱水抬头时吸气，前伸入水后缓慢呼气。",
    safety: "肩、膝或腰出现锐痛时立即停止，不要用疲劳动作硬游。",
  },
  mobility: {
    visual: singleVisual("./assets/exercises/butterfly-stretch-main.webp", "髋部放松"),
    muscleMap: "./assets/muscles/mobility.svg",
    primary: ["髋内收肌", "臀部"],
    secondary: ["肩背", "大腿后侧"],
    steps: [
      "选择肩、背、髋和腿后侧各一个舒适拉伸动作。",
      "进入轻微牵拉感后保持20至30秒，期间正常呼吸。",
      "每侧做一到两轮，不追求疼痛或极限幅度。",
    ],
    cues: ["动作缓慢进入", "保持自然呼吸", "只到轻微牵拉感"],
    mistakes: ["快速弹震", "强压关节", "把疼痛当成有效拉伸"],
    breathing: "缓慢深呼吸，呼气时稍微放松进入幅度。",
  },
  "rest-day": {
    visual: singleVisual("./assets/exercises/butterfly-stretch-main.webp", "轻松恢复"),
    muscleMap: "./assets/muscles/recovery.svg",
    primary: ["全身恢复"],
    secondary: ["关节活动", "循环放松"],
    steps: [
      "今天不安排正式力量训练，让疲劳充分下降。",
      "可以轻松散步或做五到十分钟舒缓活动。",
      "保证正常饮食、补水和睡眠，为下一周恢复状态。",
    ],
    cues: ["恢复也是计划的一部分", "不补做错过的训练", "感觉疲劳就彻底休息"],
    mistakes: ["把休息日练成高强度有氧", "因体重波动额外加练", "熬夜后仍强行训练"],
    breathing: "保持自然、放松的呼吸。",
  },
};

window.EXERCISE_GUIDES = {
  "leg-press": GUIDE_BASE["leg-press"],
  "chest-press": GUIDE_BASE["chest-press"],
  "lat-pulldown": GUIDE_BASE["lat-pulldown"],
  "leg-curl": GUIDE_BASE["leg-curl"],
  "seated-row": GUIDE_BASE["seated-row"],
  "lateral-raise": GUIDE_BASE["lateral-raise"],
  crunch: GUIDE_BASE.crunch,
  "cardio-20": GUIDE_BASE.cardio,
  "machine-lateral-raise": GUIDE_BASE["machine-lateral-raise"],
  "reverse-fly": GUIDE_BASE["reverse-fly"],
  "triceps-pushdown": GUIDE_BASE["triceps-pushdown"],
  "biceps-curl": GUIDE_BASE["biceps-curl"],
  "crunch-plus": GUIDE_BASE.crunch,
  plank: GUIDE_BASE.plank,
  "cardio-30-a": GUIDE_BASE.cardio,
  "hack-squat": GUIDE_BASE["hack-squat"],
  "incline-press": GUIDE_BASE["incline-press"],
  "chest-supported-row": GUIDE_BASE["chest-supported-row"],
  "hip-thrust": GUIDE_BASE["hip-thrust"],
  "neutral-pulldown": GUIDE_BASE["neutral-pulldown"],
  "reverse-fly-b": GUIDE_BASE["reverse-fly"],
  "crunch-b": GUIDE_BASE.crunch,
  "cardio-short-b": GUIDE_BASE.cardio,
  "light-pulldown": GUIDE_BASE["lat-pulldown"],
  "light-row": GUIDE_BASE["seated-row"],
  "light-chest-press": GUIDE_BASE["chest-press"],
  "hip-abduction": GUIDE_BASE["hip-abduction"],
  "calf-raise": GUIDE_BASE["calf-raise"],
  "core-choice": GUIDE_BASE["core-choice"],
  "cardio-30-b": GUIDE_BASE.cardio,
  "easy-swim": GUIDE_BASE["easy-swim"],
  mobility: GUIDE_BASE.mobility,
  "rest-day": GUIDE_BASE["rest-day"],
};
