const repdbPair = (slug, startLabel = "起始", peakLabel = "收缩") => ({
  kind: "pair",
  source: "repdb",
  frames: [
    { src: `./assets/exercises/${slug}-start.webp`, label: startLabel },
    { src: `./assets/exercises/${slug}-peak.webp`, label: peakLabel },
  ],
});

const freeDbPair = (slug, startLabel = "起始", peakLabel = "收缩") => ({
  kind: "pair",
  source: "free-exercise-db",
  frames: [
    { src: `./assets/exercises/${slug}-start.jpg`, label: startLabel },
    { src: `./assets/exercises/${slug}-peak.jpg`, label: peakLabel },
  ],
});

const singleVisual = (src, label, source = "repdb") => ({
  kind: "single",
  source,
  frames: [{ src, label }],
});

const GUIDE_BASE = {
  "leg-press": {
    visual: repdbPair("leg-press", "下放", "推起"),
    muscleMap: "./assets/muscles/quads-glutes.svg",
    primary: ["股四头肌", "臀大肌"],
    secondary: ["大腿后侧", "内收肌"],
    steps: [
      "调整靠背，让臀部和下背稳定贴住靠垫。",
      "双脚与肩同宽踩稳踏板，膝盖朝脚尖方向弯曲。",
      "下放到腰背仍能贴稳的位置，再用全脚掌推起。",
    ],
    cues: ["膝盖始终跟随脚尖", "脚跟不要离开踏板", "顶端保留一点膝屈"],
    mistakes: ["膝盖向内扣", "下放过深导致骨盆卷起", "推到顶时锁死膝盖"],
    breathing: "下放吸气，推起时呼气。",
  },
  "chest-press": {
    visual: repdbPair("chest-press-machine", "打开", "推合"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌"],
    secondary: ["肱三头肌", "三角肌前束"],
    steps: [
      "调座椅至握把大致与胸中部齐平，头背贴稳。",
      "肩胛轻轻向后下方收住，手腕保持中立。",
      "向前推至手臂接近伸直，再受控回到胸部拉伸位。",
    ],
    cues: ["胸口保持打开", "肩膀远离耳朵", "肘部不要抬得过高"],
    mistakes: ["推起时耸肩", "手腕折弯", "回程过快让配重撞击"],
    breathing: "回程吸气，推起时呼气。",
  },
  "lat-pulldown": {
    visual: repdbPair("lat-pulldown", "伸展", "下拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["肱二头肌", "菱形肌", "斜方肌下部"],
    steps: [
      "大腿固定在压垫下，握距略宽于肩。",
      "先把肩胛向下沉，再让肘部向身体两侧下拉。",
      "拉到上胸附近，停顿后慢慢还原至背部充分伸展。",
    ],
    cues: ["想象肘部向口袋移动", "胸口微抬", "身体只需轻微后倾"],
    mistakes: ["先用手臂猛拽", "身体大幅后仰", "把横杆拉到颈后"],
    breathing: "还原吸气，下拉时呼气。",
  },
  "leg-curl": {
    visual: repdbPair("seated-leg-curl", "伸展", "屈膝"),
    muscleMap: "./assets/muscles/hamstrings.svg",
    primary: ["腘绳肌"],
    secondary: ["腓肠肌"],
    steps: [
      "让器械转轴与膝关节大致对齐，压垫固定大腿。",
      "脚踝垫放在小腿下端，臀部和腰背贴稳。",
      "用大腿后侧把脚跟向下后方卷，停顿后慢放。",
    ],
    cues: ["大腿不要离开坐垫", "顶峰夹紧一秒", "回程保持控制"],
    mistakes: ["臀部抬起", "用惯性甩动", "回程直接松掉配重"],
    breathing: "伸膝吸气，屈膝发力时呼气。",
  },
  "seated-row": {
    visual: repdbPair("wide-grip-seated-cable-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌", "菱形肌"],
    secondary: ["三角肌后束", "肱二头肌"],
    steps: [
      "坐稳并保持脊柱自然，手臂前伸让背部得到拉伸。",
      "先收肩胛，再把肘部沿身体两侧向后拉。",
      "把手靠近腹部后停一下，缓慢送回。",
    ],
    cues: ["胸口朝前", "肘部向后而不是手向后", "肩膀保持下沉"],
    mistakes: ["反复前后甩动身体", "耸肩拉动", "只弯手肘没有收背"],
    breathing: "前伸吸气，后拉时呼气。",
  },
  "lateral-raise": {
    visual: repdbPair("lateral-raise", "垂臂", "抬臂"),
    muscleMap: "./assets/muscles/side-delts.svg",
    primary: ["三角肌中束"],
    secondary: ["冈上肌", "斜方肌"],
    steps: [
      "站稳，手肘微弯，哑铃放在身体两侧。",
      "让手肘带动手臂向侧上方抬起。",
      "抬到接近肩高后停顿，再慢慢下放。",
    ],
    cues: ["重量宁轻不甩", "手肘略高于手腕", "肩膀远离耳朵"],
    mistakes: ["借腰腿摆动", "耸肩代偿", "抬得过高并内旋手臂"],
    breathing: "下放吸气，抬起时呼气。",
  },
  "machine-lateral-raise": {
    visual: repdbPair("seated-dumbbell-lateral-raise", "垂臂", "抬臂"),
    muscleMap: "./assets/muscles/side-delts.svg",
    primary: ["三角肌中束"],
    secondary: ["冈上肌", "斜方肌"],
    steps: [
      "调座椅让器械转轴接近肩关节，背部贴稳。",
      "手肘或前臂贴住垫子，用手肘向外上方带动。",
      "抬至接近肩高，短暂停顿后受控下放。",
    ],
    cues: ["手臂只是杠杆", "肩膀不要耸起", "全程保持同一轨迹"],
    mistakes: ["用身体弹起重量", "座椅过高或过低", "下放时配重直接落到底"],
    breathing: "下放吸气，抬起时呼气。",
  },
  "reverse-fly": {
    visual: repdbPair("dumbbell-reverse-fly", "合拢", "展开"),
    muscleMap: "./assets/muscles/rear-delts.svg",
    primary: ["三角肌后束"],
    secondary: ["菱形肌", "斜方肌中部"],
    steps: [
      "俯身或贴稳胸垫，脊柱保持自然，手肘微弯。",
      "手臂向两侧展开，想象用手肘带动。",
      "肩后侧收紧后停一下，再慢慢回到起始位。",
    ],
    cues: ["肩膀保持下沉", "手肘轨迹略低于肩", "用小重量找后束"],
    mistakes: ["耸肩夹背过多", "甩动躯干", "手臂伸得过直并锁肘"],
    breathing: "合拢吸气，展开时呼气。",
  },
  "triceps-pushdown": {
    visual: repdbPair("tricep-pushdown", "屈肘", "下压"),
    muscleMap: "./assets/muscles/triceps.svg",
    primary: ["肱三头肌"],
    secondary: ["前臂肌群"],
    steps: [
      "站稳并略微前倾，把肘部固定在身体两侧。",
      "向下伸直手肘，绳索动作可在底端稍向两边分开。",
      "肱三头肌收紧后，缓慢回到前臂接近水平的位置。",
    ],
    cues: ["只让前臂转动", "手腕保持中立", "底端完全收紧但不甩"],
    mistakes: ["肘部前后飘动", "用身体重量下压", "回程过高让肩部接管"],
    breathing: "回程吸气，下压时呼气。",
  },
  "biceps-curl": {
    visual: repdbPair("bicep-curl", "伸肘", "弯举"),
    muscleMap: "./assets/muscles/biceps.svg",
    primary: ["肱二头肌"],
    secondary: ["肱肌", "肱桡肌"],
    steps: [
      "站稳并收紧核心，肘部放在身体两侧。",
      "保持上臂稳定，把重量弯举到二头肌充分收紧。",
      "慢慢伸肘回到起始位，不要直接掉下去。",
    ],
    cues: ["肘部像钉在身侧", "顶峰不抬肩", "下放比举起更慢"],
    mistakes: ["甩腰借力", "肘部向前跑", "动作只做一半"],
    breathing: "下放吸气，弯举时呼气。",
  },
  crunch: {
    visual: repdbPair("crunches", "伸展", "卷起"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹直肌"],
    secondary: ["腹斜肌"],
    steps: [
      "仰卧屈膝，腰背自然贴近垫面，手轻放头侧或胸前。",
      "先收紧腹部，再把肩胛骨卷离地面。",
      "停顿后逐节慢慢回落，不需要坐起。",
    ],
    cues: ["肋骨向骨盆靠近", "下巴与胸口留一拳", "动作幅度小而稳定"],
    mistakes: ["双手拉脖子", "用髋屈肌直接坐起", "憋气猛卷"],
    breathing: "下放吸气，卷起时缓慢呼气。",
  },
  plank: {
    visual: singleVisual("./assets/exercises/plank-main.webp", "稳定支撑"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹横肌", "腹直肌"],
    secondary: ["臀肌", "肩部稳定肌"],
    steps: [
      "肘部放在肩膀正下方，前臂压稳地面。",
      "伸直双腿，收紧腹部和臀部，让身体成一条直线。",
      "保持自然呼吸，在姿势开始变形前结束。",
    ],
    cues: ["尾骨微收", "肋骨不要外翻", "用肘部推开地面"],
    mistakes: ["塌腰或撅臀", "低头憋气", "为了时长牺牲姿势"],
    breathing: "保持均匀呼吸，每次呼气时轻收腹部。",
  },
  "hack-squat": {
    visual: repdbPair("hack-squat", "下蹲", "站起"),
    muscleMap: "./assets/muscles/quads-glutes.svg",
    primary: ["股四头肌", "臀大肌"],
    secondary: ["内收肌", "腘绳肌"],
    steps: [
      "肩背贴稳靠垫，双脚与肩同宽踩在踏板上。",
      "解锁后屈膝下蹲，膝盖沿脚尖方向移动。",
      "下到腰背仍稳定的位置，用全脚掌发力站起。",
    ],
    cues: ["脚掌三点压稳", "膝盖不内扣", "臀背始终贴垫"],
    mistakes: ["脚跟抬起", "底部骨盆卷起", "顶端猛锁膝盖"],
    breathing: "下蹲吸气，站起时呼气。",
  },
  "incline-press": {
    visual: repdbPair("smith-machine-incline-bench-press", "下放", "推起"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌上部"],
    secondary: ["三角肌前束", "肱三头肌"],
    steps: [
      "调好座椅或靠背，让推举轨迹落在上胸位置。",
      "肩胛向后下方固定，双脚踩稳，手腕保持中立。",
      "受控下放到舒适深度，再向上推至接近伸直。",
    ],
    cues: ["胸口微抬", "前臂尽量垂直", "肩膀不要向前顶"],
    mistakes: ["角度过高变成肩推", "肘部张到正侧方", "腰部过度拱起"],
    breathing: "下放吸气，推起时呼气。",
  },
  "chest-supported-row": {
    visual: repdbPair("chest-supported-db-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌", "菱形肌"],
    secondary: ["三角肌后束", "肱二头肌"],
    steps: [
      "胸口贴稳支撑垫，双脚固定，手臂自然前伸。",
      "先收肩胛，再让肘部向后拉过身体。",
      "背部收紧后停顿，缓慢伸臂回到完整拉伸。",
    ],
    cues: ["胸不离垫", "肩膀保持下沉", "肘部决定拉向位置"],
    mistakes: ["抬胸离开支撑", "耸肩拉动", "用手腕向上勾重量"],
    breathing: "前伸吸气，后拉时呼气。",
  },
  "hip-thrust": {
    visual: repdbPair("hip-thrust", "下放", "顶髋"),
    muscleMap: "./assets/muscles/glutes.svg",
    primary: ["臀大肌"],
    secondary: ["腘绳肌", "内收肌"],
    steps: [
      "让上背稳定靠住支撑，双脚踩稳，顶端小腿接近垂直。",
      "收紧腹部并保持下巴微收，用臀部把髋推起。",
      "顶端让躯干与大腿接近一线，夹臀后慢慢下放。",
    ],
    cues: ["肋骨收住", "脚跟发力", "顶端夹臀而不是仰腰"],
    mistakes: ["用腰椎过伸顶起", "脚离身体太远或太近", "头部后仰"],
    breathing: "下放吸气，顶髋时呼气。",
  },
  "neutral-pulldown": {
    visual: repdbPair("v-bar-lat-pulldown", "伸展", "下拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["肱二头肌", "菱形肌"],
    steps: [
      "用中立握把坐稳，大腿固定，胸口微抬。",
      "先让肩胛下沉，再把肘部朝身体两侧向下拉。",
      "握把靠近上胸后停顿，受控回到手臂伸展位。",
    ],
    cues: ["肘向下走", "手只是挂钩", "躯干保持稳定"],
    mistakes: ["用手臂先发力", "大幅后仰借力", "回程耸肩失控"],
    breathing: "还原吸气，下拉时呼气。",
  },
  "hip-abduction": {
    visual: repdbPair("hip-abduction", "合拢", "外展"),
    muscleMap: "./assets/muscles/hip-abductors.svg",
    primary: ["臀中肌", "臀小肌"],
    secondary: ["阔筋膜张肌"],
    steps: [
      "坐稳并让背部贴住靠垫，双脚放稳。",
      "保持骨盆不动，用臀部把双腿向外打开。",
      "外展到可控范围后停一下，再缓慢合拢。",
    ],
    cues: ["髋部发力", "膝盖匀速打开", "回程仍保持张力"],
    mistakes: ["身体前后摆动", "靠弹力快速开合", "配重回落时完全放松"],
    breathing: "合拢吸气，外展时呼气。",
  },
  "calf-raise": {
    visual: repdbPair("machine-calf-raise", "下沉", "提踵"),
    muscleMap: "./assets/muscles/calves.svg",
    primary: ["腓肠肌", "比目鱼肌"],
    secondary: ["足底稳定肌"],
    steps: [
      "前脚掌踩稳踏台，脚跟悬空，膝盖保持自然。",
      "先让脚跟缓慢下沉，感受小腿完整拉伸。",
      "用前脚掌推起脚跟，顶端停一下后慢慢下放。",
    ],
    cues: ["脚踝直上直下", "顶端充分收紧", "底部停顿不要弹"],
    mistakes: ["动作幅度过小", "脚踝向内外翻", "借膝盖弹动"],
    breathing: "下沉吸气，提踵时呼气。",
  },
  "core-choice": {
    visual: repdbPair("crunches", "伸展", "卷起"),
    muscleMap: "./assets/muscles/core.svg",
    primary: ["腹直肌", "腹横肌"],
    secondary: ["腹斜肌", "髋部稳定肌"],
    steps: [
      "从卷腹、死虫或平板支撑中选一个当天最稳的动作。",
      "先收紧腹部并固定骨盆，再开始四肢动作。",
      "腰背失去控制时立即结束这一组。",
    ],
    cues: ["肋骨和骨盆保持对齐", "动作慢且可控", "质量优先于次数"],
    mistakes: ["腰部拱起或塌下", "屏住呼吸", "只追次数忽略稳定"],
    breathing: "保持连续呼吸，最费力阶段缓慢呼气。",
  },
  "assisted-dip": {
    visual: freeDbPair("assisted-dip", "下放", "推起"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌下部"],
    secondary: ["肱三头肌", "三角肌前束"],
    steps: [
      "选择能让动作稳定的辅助重量，双手撑稳并让胸廓打开。",
      "身体稍微前倾，肘部向后外侧弯曲，受控下放到肩部舒适的位置。",
      "保持胸部张力推起，接近伸直后停住，不用肩膀向前顶。",
    ],
    cues: ["胸部先建立张力", "前倾角度保持不变", "肩前侧无挤压感"],
    mistakes: ["为了深度让肩膀前顶", "身体上下弹动", "辅助太少导致动作变形"],
    breathing: "下放吸气，推起时呼气。",
    safety: "肩前侧出现锐痛或明显夹挤感时停止，改用坐姿推胸器。",
  },
  "reverse-grip-pulldown": {
    visual: freeDbPair("reverse-grip-pulldown", "伸展", "下拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["肱二头肌", "大圆肌"],
    steps: [
      "反握略窄于肩，固定大腿，让躯干保持稳定。",
      "先让背阔肌建立张力并沉肩，再把肘部朝髋部方向拉。",
      "把杆拉到上胸附近，在身体准备后仰前停止，再受控还原。",
    ],
    cues: ["手只是挂钩", "肘部朝髋部移动", "腰和头保持固定"],
    mistakes: ["用二头肌猛拽", "大幅后仰缩短动作", "回程直接耸肩卸力"],
    breathing: "还原吸气，下拉时呼气。",
  },
  "narrow-neutral-row": {
    visual: freeDbPair("narrow-neutral-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["菱形肌", "肱二头肌"],
    steps: [
      "使用窄中立握把坐稳，脚掌踩实，腰背保持自然。",
      "先锁定下肢和躯干，再让肘部贴近身体向后移动。",
      "握把靠近下腹时停止，保持张力慢慢前送。",
    ],
    cues: ["下肢不参与借力", "肘贴身体拉向后", "动作幅度服从背部张力"],
    mistakes: ["反复前后甩腰", "肩膀耸起", "只弯手肘没有带动背部"],
    breathing: "前送吸气，后拉时呼气。",
  },
  "straight-arm-pulldown": {
    visual: freeDbPair("straight-arm-pulldown", "上举伸展", "下压"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["背阔肌"],
    secondary: ["大圆肌", "肱三头肌长头"],
    steps: [
      "站在高位滑轮前，髋部轻微后移，手肘保持微屈。",
      "先收紧背阔肌，再沿弧线把手臂压向大腿。",
      "手臂上举到背部仍能控制的位置，不为了拉伸耸肩或塌腰。",
    ],
    cues: ["手肘角度固定", "躯干不跟着起伏", "想象腋下向髋部收紧"],
    mistakes: ["变成肱三头肌下压", "用体重向下砸", "回程过高失去背部张力"],
    breathing: "上举吸气，下压时呼气。",
  },
  "rear-delt-extension": {
    visual: freeDbPair("rear-delt-extension", "前方起始", "向后展开"),
    muscleMap: "./assets/muscles/rear-delts.svg",
    primary: ["三角肌后束"],
    secondary: ["小圆肌", "菱形肌"],
    steps: [
      "调整绳索高度，站稳并让胸廓、骨盆保持对齐。",
      "手臂近乎伸直，从肩关节向后外侧展开。",
      "后束收紧后停一下，在躯干转动或耸肩前结束动作。",
    ],
    cues: ["躯干像支架一样稳定", "肩后侧带动", "小重量完成高质量次数"],
    mistakes: ["转动身体借力", "夹背过多抢走后束发力", "为了幅度把肩向前顶"],
    breathing: "回程吸气，向后展开时呼气。",
  },
  "leg-extension": {
    visual: freeDbPair("leg-extension", "屈膝", "伸膝"),
    muscleMap: "./assets/muscles/quads-glutes.svg",
    primary: ["股四头肌"],
    secondary: ["髋部稳定肌"],
    steps: [
      "让器械转轴与膝关节对齐，小腿垫放在脚踝上方。",
      "臀部和背部贴稳座椅，用股四头肌把小腿抬起。",
      "顶端收紧后慢慢下放，配重片不要撞到底。",
    ],
    cues: ["膝盖正对前方", "顶峰主动收紧", "回程保持控制"],
    mistakes: ["用身体弹起重量", "座椅位置不合适", "快速甩腿并锁死膝盖"],
    breathing: "下放吸气，伸膝时呼气。",
  },
  "shoulder-press": {
    visual: freeDbPair("shoulder-press", "下放", "推起"),
    muscleMap: "./assets/muscles/side-delts.svg",
    primary: ["三角肌前束", "三角肌中束"],
    secondary: ["肱三头肌", "上胸"],
    steps: [
      "坐在有靠背的训练椅上，双脚踩稳，哑铃放到肩部两侧。",
      "收紧腹部并保持胸廓稳定，让前臂接近垂直。",
      "向上推到手臂接近伸直，再受控下放到肩部舒适深度。",
    ],
    cues: ["背部贴稳", "手肘跟随手腕", "先稳定再加重量"],
    mistakes: ["腰部大幅反弓", "哑铃相撞", "下放过深导致肩前侧不适"],
    breathing: "下放吸气，推起时呼气。",
  },
  "low-cable-fly": {
    visual: freeDbPair("low-cable-fly", "打开", "向上夹合"),
    muscleMap: "./assets/muscles/chest-push.svg",
    primary: ["胸大肌上部"],
    secondary: ["三角肌前束", "肱二头肌短头"],
    steps: [
      "将滑轮调到低位，前后站稳，手臂在身体两侧下方展开。",
      "固定胸廓和手肘角度，把双手沿弧线向上、向内合拢。",
      "胸部收紧后沿原轨迹返回，在肩部仍稳定的位置停止。",
    ],
    cues: ["胸廓不跟着抬起", "手肘角度保持不变", "用上胸完成夹合"],
    mistakes: ["变成前平举", "腰部后仰借力", "双手过度交叉失去张力"],
    breathing: "打开吸气，夹合时呼气。",
  },
  "overhead-triceps": {
    visual: freeDbPair("overhead-triceps", "屈肘拉伸", "伸肘"),
    muscleMap: "./assets/muscles/triceps.svg",
    primary: ["肱三头肌长头"],
    secondary: ["核心稳定肌"],
    steps: [
      "将绳索接在低位滑轮，背对器械站稳，双手举过头顶。",
      "上臂固定在头部两侧，弯肘让绳索落到头后。",
      "只伸直手肘完成动作，顶端收紧后慢慢还原。",
    ],
    cues: ["上臂保持不动", "肋骨收住", "感受三头长头拉伸"],
    mistakes: ["腰部反弓", "肘部向两侧散开", "用肩膀推拉绳索"],
    breathing: "屈肘吸气，伸肘时呼气。",
  },
  "upper-back-row": {
    visual: freeDbPair("upper-back-row", "前伸", "后拉"),
    muscleMap: "./assets/muscles/back-pull.svg",
    primary: ["菱形肌", "斜方肌中部"],
    secondary: ["三角肌后束", "肱二头肌"],
    steps: [
      "坐稳并保持躯干直立，使用较宽或绳索中立握法。",
      "肘部略向外抬，先让肩胛向后收，再把握把拉向上腹或下胸。",
      "肩胛充分收紧后停顿，受控前送到上背得到伸展。",
    ],
    cues: ["肘部向外后方走", "腰部保持固定", "肩胛后缩而不是耸肩"],
    mistakes: ["后仰借力", "把肘压得太低变成背阔肌划船", "回程直接放掉配重"],
    breathing: "前送吸气，后拉时呼气。",
  },
  "hammer-curl": {
    visual: freeDbPair("hammer-curl", "伸肘", "弯举"),
    muscleMap: "./assets/muscles/biceps.svg",
    primary: ["肱肌", "肱桡肌"],
    secondary: ["肱二头肌", "前臂肌群"],
    steps: [
      "站稳并保持掌心相对，肘部放在身体两侧。",
      "固定上臂，把哑铃向肩部方向弯举。",
      "顶端短暂停顿，再控制哑铃回到手臂伸展位。",
    ],
    cues: ["掌心始终相对", "肘部不向前跑", "下放保持张力"],
    mistakes: ["甩腰借力", "耸肩抬起重量", "只做半程"],
    breathing: "下放吸气，弯举时呼气。",
  },
  cardio: {
    visual: {
      kind: "pair",
      source: "mixed",
      frames: [
        { src: "./assets/exercises/walking-treadmill-start.jpg", label: "稳定步态" },
        { src: "./assets/exercises/air-bike-main.webp", label: "单车选项" },
      ],
    },
    muscleMap: "./assets/muscles/cardio-lower.svg",
    primary: ["股四头肌", "臀肌", "小腿"],
    secondary: ["腘绳肌", "心肺系统"],
    steps: [
      "力量训练后先用低强度进入节奏，再逐步调到目标坡度或阻力。",
      "保持能说短句的中等强度，步幅和踩踏节奏稳定。",
      "最后两分钟降低强度，让呼吸慢慢恢复。",
    ],
    cues: ["扶手只用于保持平衡", "身体不要趴在机器上", "腿很累就主动降强度"],
    mistakes: ["一开始就把强度拉满", "紧抓扶手抵消坡度", "腿部主训练后仍硬撑高坡"],
    breathing: "保持连续、规律的呼吸，不要憋气。",
  },
  "easy-swim": {
    visual: singleVisual("./assets/exercises/breaststroke.gif", "蛙泳动作循环", "wikimedia"),
    muscleMap: "./assets/muscles/swim-full.svg",
    primary: ["背阔肌", "胸肌", "大腿内侧"],
    secondary: ["肩部", "臀腿", "核心"],
    steps: [
      "双臂前伸滑行，随后向外抱水并抬头换气。",
      "手臂前伸时收腿，脚跟靠近臀部。",
      "脚掌外翻后向后蹬夹，身体重新伸直滑行。",
    ],
    cues: ["先抱水再换气", "蹬夹后留出滑行", "以轻松恢复为主"],
    mistakes: ["抬头过高导致腰背紧张", "只蹬不夹", "全程抢节奏没有滑行"],
    breathing: "抱水抬头时吸气，前伸入水后缓慢呼气。",
    safety: "肩、膝或腰出现锐痛时立即停止，不要用疲劳动作硬游。",
  },
  mobility: {
    visual: singleVisual("./assets/exercises/butterfly-stretch-main.webp", "髋部放松"),
    muscleMap: "./assets/muscles/mobility.svg",
    primary: ["髋内收肌", "臀部"],
    secondary: ["肩背", "大腿后侧"],
    steps: [
      "选择肩、背、髋和腿后侧各一个舒适拉伸动作。",
      "进入轻微牵拉感后保持20至30秒，期间正常呼吸。",
      "每侧做一到两轮，不追求疼痛或极限幅度。",
    ],
    cues: ["动作缓慢进入", "保持自然呼吸", "只到轻微牵拉感"],
    mistakes: ["快速弹震", "强压关节", "把疼痛当成有效拉伸"],
    breathing: "缓慢深呼吸，呼气时稍微放松进入幅度。",
  },
  "rest-day": {
    visual: singleVisual("./assets/exercises/butterfly-stretch-main.webp", "轻松恢复"),
    muscleMap: "./assets/muscles/recovery.svg",
    primary: ["全身恢复"],
    secondary: ["关节活动", "循环放松"],
    steps: [
      "今天不安排正式力量训练，让疲劳充分下降。",
      "可以轻松散步或做五到十分钟舒缓活动。",
      "保证正常饮食、补水和睡眠，为下一周恢复状态。",
    ],
    cues: ["恢复也是计划的一部分", "不补做错过的训练", "感觉疲劳就彻底休息"],
    mistakes: ["把休息日练成高强度有氧", "因体重波动额外加练", "熬夜后仍强行训练"],
    breathing: "保持自然、放松的呼吸。",
  },
};

const COACH_VIDEO_DETAILS = {
  "assisted-dip": {
    coach: {
      session: "谭成义 · 胸部教学",
      time: "07:12-14:38",
      focus: "挺胸、髋部向后，整体保持微前倾；只在胸部持续有张力且肩部舒服的幅度内上下。",
      points: [
        { label: "准备", text: "先用辅助重量把姿势做稳。胸廓打开，腹部收紧，髋部向后，让身体形成轻微前倾。" },
        { label: "轨迹", text: "下放和推起时前倾角度都不变，不要在底部前倾、推起后又变成直立。" },
        { label: "收缩", text: "保持胸廓扩张，把胸推到能主动收紧的位置即可；不要为追求更近而含胸、圆肩。" },
        { label: "幅度", text: "深度由肩关节舒适度决定。肩前侧出现夹挤感时增加辅助或缩短下放。" },
      ],
    },
    steps: [
      "选择能稳定完成动作的辅助重量，撑稳后挺胸、收腹，髋部稍向后并保持微前倾。",
      "肘部向后外侧弯曲，沿同一前倾角度受控下放，不追求超过肩部能力的深度。",
      "保持胸廓位置推起，在胸部已经收紧、肩膀准备向前顶之前结束。",
    ],
    cues: ["髋向后，身体微前倾", "上下保持同一角度", "胸紧就停，不含胸硬夹"],
    mistakes: ["推起后身体变直", "核心松掉、身体弹动", "肩膀前顶还继续下放"],
    breathing: "下放前吸气撑开胸廓并收紧核心；推起时缓慢呼气，但胸廓不要塌掉。",
  },
  "chest-press": {
    coach: {
      session: "谭成义 · 胸部教学",
      time: "14:39-21:24",
      focus: "腰贴靠背、胸廓扩张，把胸收紧即可；不要为了推得更远让肩和肋骨一起向前塌。",
      points: [
        { label: "坐姿", text: "调整座椅让握把对准中下胸。腰背尽量贴住靠垫，再通过吸气把胸廓前侧撑开。" },
        { label: "握法", text: "视频在推胸器上更偏向半握和尺侧发力；若机器握把不稳，优先全握，安全比模仿握法重要。" },
        { label: "推起", text: "肩部保持稳定，把胸推到最紧；不需要继续送肩、内旋手臂或把肋骨压塌来换取距离。" },
        { label: "呼气", text: "推出时可以呼气，但胸腔扩张不能随呼气消失。腰一离垫或肩一前顶，这次就到头了。" },
      ],
    },
    steps: [
      "把腰背贴稳，吸气让胸廓扩张，握把与中下胸大致同高。",
      "保持胸廓和肩部位置向前推，手腕、前臂与器械阻力方向对齐。",
      "胸部完全收紧后停止，不送肩；受控回到仍能维持胸廓和肩部稳定的位置。",
    ],
    cues: ["腰贴住再开胸", "胸收紧，不送肩", "呼气时胸廓不塌"],
    mistakes: ["用拱腰代替开胸", "顶端把肩膀完全推出去", "回程过深导致肩前侧受压"],
    breathing: "先吸气扩张胸廓；推起时缓慢呼气并维持胸廓，回程再补气。",
  },
  "incline-press": {
    coach: {
      session: "谭成义 · 胸部教学",
      time: "21:24-28:32",
      focus: "腰贴、肋骨略收，肘稍抬高沿上胸线推；回程不用追求深，主要把上胸推紧。",
      points: [
        { label: "靠背", text: "这套做法使用偏直的上斜轨迹。腰贴靠背、肋骨稍收，避免挺胸过多后又变成中下胸发力。" },
        { label: "手肘", text: "手肘比常见上斜推略高，前臂顺着上胸纤维方向推；手臂明显抢力时可适当调宽握距。" },
        { label: "回程", text: "下放到肩和上胸仍能稳定的位置即可，不必追求很深；视频强调这组以推和收紧为主。" },
        { label: "停止", text: "腰离垫、下胸明显顶起、肩膀前移，或左右轨迹开始不一致时，立刻结束该次。" },
      ],
    },
    steps: [
      "调整座椅和握距，让推举轨迹对准上胸；腰贴稳，肋骨略微收住。",
      "手肘稍抬高，沿上胸方向推起，肩膀不要向耳朵或前方跑。",
      "上胸收紧后受控下放，在胸廓或肩部准备变形之前回推。",
    ],
    cues: ["腰贴、肋骨略收", "肘稍高，沿上胸推", "回程不贪深"],
    mistakes: ["拱腰变成中下胸推", "手肘太低、手臂抢力", "为了拉伸让肩膀前顶"],
    breathing: "姿势固定后吸气；推起时呼气，回程保持腹部和胸廓位置。",
  },
  "low-cable-fly": {
    coach: {
      session: "谭成义 · 胸部教学",
      time: "28:32-33:07",
      focus: "滑轮约膝高，腰背稳定、肋骨收住，双手夹到鼻子前；回到胸廓将变化前就停。",
      points: [
        { label: "滑轮", text: "滑轮大致放在膝盖高度，从低位向上、向内夹；最终方向约在鼻子正前方。" },
        { label: "高度", text: "夹得太高会让肩膀参与更多，太低则更像平夹。根据上胸收缩感微调，不照搬固定档位。" },
        { label: "回程", text: "只回到肋骨和胸廓仍能固定的位置。继续后放若需要挺胸、开肋或动肩胛，就已经超出有效幅度。" },
        { label: "向心", text: "先保证每次都能把上胸夹紧，再考虑增加回程和重量；找不到收缩时不要追求大拉伸。" },
      ],
    },
    steps: [
      "将滑轮调到约膝高，前后站稳，腰背稳定并把肋骨收住。",
      "保持手肘角度，用上胸把双手沿弧线夹向鼻子正前方。",
      "夹紧后沿原轨迹返回，在胸廓、腰或肩胛准备移动之前停止。",
    ],
    cues: ["膝高滑轮，夹向鼻前", "先夹紧，再谈拉伸", "肋骨位置全程不变"],
    mistakes: ["夹得太高变成肩前束", "回程过大并挺胸开肋", "只合手，没有主动收上胸"],
    breathing: "回程吸气并保持肋骨稳定；夹合时呼气，把上胸主动收紧。",
  },
  "reverse-grip-pulldown": {
    coach: {
      session: "谭成义 · 背部教学",
      time: "05:18-07:21",
      focus: "与肩同宽反握，微前倾，背先预紧再让肘往里下拉；回程腹部绷紧，不让肩膀耸上去。",
      points: [
        { label: "握距", text: "反握约与肩同宽。视频用半握帮助尺侧发力；不熟悉或握把易滑时请全握。" },
        { label: "启动", text: "先把杆拉到可控位置，深吸气让背阔肌预先发力，再微微前倾、把肘往身体内侧收。" },
        { label: "回程", text: "腹部持续绷紧，肩膀不要跟着重量耸上去；回到背阔肌仍有张力的位置，不必完全卸力。" },
        { label: "收缩", text: "下拉时同时做到胸口打开和背阔肌收紧。若出现含胸、后仰或腰部顶起，重量已经过重。" },
      ],
    },
    steps: [
      "反握约与肩同宽，固定大腿；深吸气让背先预紧，身体保持轻微前倾。",
      "肘部往里收并朝髋部方向下拉，胸口打开，但身体不后仰。",
      "收紧后缓慢上送，腹部继续绷紧，肩膀耸起或背部松掉前停止。",
    ],
    cues: ["背先紧，肘再拉", "微前倾，不后仰", "挺胸与收背同时做"],
    mistakes: ["二头肌先猛拽", "回程耸肩完全卸力", "为拉得更低而含胸顶腰"],
    breathing: "开始前深吸气并收紧腹部；下拉时呼气，回程补气但不要把张力放掉。",
  },
  "narrow-neutral-row": {
    coach: {
      session: "谭成义 · 背部教学",
      time: "07:35-13:31",
      focus: "双脚主动蹬稳、腿后侧发力，背先预紧；微前倾向斜下方拉，宁可短幅也不后仰、顶腰。",
      points: [
        { label: "下肢", text: "双脚主动蹬住踏板，让腿后侧发力，先把骨盆和腰椎固定；下肢松散时腰部很容易代偿。" },
        { label: "启动", text: "先把握把拉回一小段，让背阔肌预紧，深吸气保持住，再开始正式后拉。" },
        { label: "方向", text: "身体微前倾，肘贴身向斜下方拉。后仰或把手抬向斜上方，会把刺激转向上背。" },
        { label: "幅度", text: "只做到背阔肌还能主导的位置。再拉需要抬胸、后仰或顶腰时，即使握把没碰到身体也该结束。" },
        { label: "颈部", text: "下巴轻收、头向后延伸，保持颈部中立；回程也不要为了拉伸把背部完全放松。" },
      ],
    },
    steps: [
      "窄中立握坐稳，双脚用力蹬住踏板，让腿后侧发力并固定骨盆。",
      "先小幅拉回建立背阔肌张力，吸气收紧核心，身体保持微前倾。",
      "肘贴身向斜下方拉，在躯干准备后仰、抬胸或顶腰前停止，再受控前送。",
    ],
    cues: ["脚蹬稳，腿后侧发力", "背先预紧再划", "向斜下拉，短幅也可以"],
    mistakes: ["下肢放松让腰接管", "为碰到腹部而后仰", "回程过远让背阔肌松掉"],
    breathing: "预紧后深吸气固定核心；后拉时呼气，回程受控补气。",
  },
  "neutral-pulldown": {
    coach: {
      session: "谭成义 · 背部教学",
      time: "13:31-16:34",
      focus: "微前倾、腹部绷紧，拉到口鼻附近；回程留一点，重点找大圆肌和肩胛上回旋的拉伸。",
      points: [
        { label: "目标", text: "这版中距离对握下拉不追求拉得越低，而是强调大圆肌拉伸和肩胛上回旋的体感。" },
        { label: "姿势", text: "深吸气后重心微微前倾，腹部收紧，胸廓保持稳定；不要后仰或用腰向前顶。" },
        { label: "终点", text: "握把拉到嘴巴或鼻子附近即可。继续往下若需要扣肩、含胸或后仰，就失去本动作目的。" },
        { label: "回程", text: "上送时留一点距离，不把配重完全放到底；保持身体刚性，同时感受肩胛上回旋的拉伸。" },
      ],
    },
    steps: [
      "中立握坐稳，深吸气收紧腹部，让重心保持轻微前倾。",
      "在躯干不动的情况下下拉，到握把接近口鼻位置即可。",
      "受控上送并保留一点距离，找到大圆肌和肩胛上回旋拉伸后再次下拉。",
    ],
    cues: ["拉到口鼻，不求更低", "腹紧、身体微前倾", "回程留一点张力"],
    mistakes: ["后仰把握把拉到胸口", "扣肩或含胸完成末端", "回程到底后完全卸力"],
    breathing: "下拉前吸气建立身体刚性；下拉时呼气，回程补气并维持腹部张力。",
  },
  "upper-back-row": {
    coach: {
      session: "谭成义 · 背部教学",
      time: "16:34-19:12",
      focus: "中立坐稳、肘打开，肩胛后缩主导；回程只到约三分之二，头和腰都固定。",
      points: [
        { label: "区别", text: "它和窄握划船的关键区别是肘部打开，训练重点从背阔肌肩伸转为中上背的肩胛后缩。" },
        { label: "躯干", text: "保持中立位，收紧核心、双腿蹬稳；头部和腰部都固定，不用后仰或顶腰增加幅度。" },
        { label: "发力", text: "先让肩胛向两侧后方收紧，再让手臂跟随。想的是肩胛后缩，不是把握把硬拽到身体。" },
        { label: "回程", text: "前送大约到完整行程的三分之二，保留约三分之一，不让肩胛和上背完全松掉。" },
      ],
    },
    steps: [
      "坐在中立位，双脚蹬稳并收紧核心，肘部略向外打开。",
      "头和腰保持固定，用肩胛后缩带动手臂向后。",
      "肩胛收紧后受控前送到约三分之二，在上背仍有张力的位置再次后拉。",
    ],
    cues: ["开肘练中上背", "肩胛先动，手臂跟随", "头腰固定，回程留三分之一"],
    mistakes: ["后仰或顶腰换幅度", "只弯手肘不收肩胛", "回程到底完全放松"],
    breathing: "后拉前吸气固定核心；肩胛后缩时呼气，回程平稳补气。",
  },
  "straight-arm-pulldown": {
    coach: {
      session: "谭成义 · 背部教学",
      time: "19:12-23:32",
      focus: "握距约1.2至1.5倍肩宽，手腕扣住、肘微抬；背先预紧，再用髋部小幅屈伸配合下压。",
      points: [
        { label: "握法", text: "握距约为肩宽的1.2至1.5倍，半握或全握都可；手腕略向下扣，手肘微微抬高。" },
        { label: "预紧", text: "先把杆拉下建立位置，微前倾、腹部绷紧，深吸气让背预先发力，再开始下压。" },
        { label: "进阶", text: "视频版在腰椎中立的前提下，用髋关节小幅屈伸配合手臂下压，以覆盖上下段背阔肌；不是用腰甩。" },
        { label: "退阶", text: "不会协调时先固定躯干：固定俯身更偏上段，接近直立更偏下段。任一版本都先保证背部收紧。" },
        { label: "停止", text: "后仰、含胸、肩或三头先酸，通常说明背没有预紧或重量过大；减重并重新建立起始张力。" },
      ],
    },
    steps: [
      "用约1.2至1.5倍肩宽握距站稳，手腕略扣、肘微抬，腹部收紧并让背先预紧。",
      "保持腰椎中立，把手臂压向大腿；熟练后可加入小幅屈髋与伸髋配合。",
      "背部收紧到位后受控回程，肩膀、三头或腰部开始抢力前结束。",
    ],
    cues: ["背先预紧再下压", "手腕扣住，肘微抬", "动髋不甩腰"],
    mistakes: ["背没发力就直接砸下", "后仰挤压下段背阔", "含胸或屈肘变成三头下压"],
    breathing: "起始深吸气并固定腹部；下压时呼气，回程保持背部张力。",
  },
  "rear-delt-extension": {
    coach: {
      session: "谭成义 · 肩部教学",
      time: "05:43-14:02",
      focus: "轻重量、肩胛下沉固定，用肩伸把手臂向后；回程幅度小，后束不能松掉。",
      points: [
        { label: "用途", text: "这组更偏后束肩伸激活，不以堆大重量为目的；先找到后束，再进入后续反向飞鸟。" },
        { label: "肩胛", text: "俯身后让肩胛保持下沉和稳定，手臂向后时不要让肩膀向前翻，也不要靠夹背代偿。" },
        { label: "幅度", text: "从后束已经有张力的位置开始，回程很小；手臂送太远会让后束松掉。抬多高取决于肩胛能否稳住。" },
        { label: "握法", text: "内旋位更孤立后束，对握更兼顾中后束衔接；正手不舒服时优先对握，不强行内旋。" },
        { label: "次数", text: "视频建议用能完成15次以上的轻重量，并在收缩处短暂停顿，关注神经募集而非重量。" },
      ],
    },
    steps: [
      "选择轻重量并俯身，胸廓稳定，让肩胛保持下沉。",
      "在肩胛不前翻、不夹背的情况下，用后束把手臂向身后伸。",
      "顶端短暂停顿，只回到后束仍有张力的位置，再次向后伸。",
    ],
    cues: ["这是激活，重量要轻", "肩胛下沉固定", "回程小，后束不断电"],
    mistakes: ["肩膀向前翻", "用肩胛后缩代替肩伸", "回程过大让后束松掉"],
    breathing: "动作前吸气稳定躯干；向后伸时呼气，回程保持肩胛位置。",
  },
  "reverse-fly": {
    coach: {
      session: "谭成义 · 肩部教学",
      time: "14:02-21:14",
      focus: "手肘与肩同高、脚往前、躯干微前倾；不是夹背，而是向远端、向外展开。",
      points: [
        { label: "座椅", text: "调整座椅让手和手肘大致与肩同高。位置过低会让肩胛悬空、斜方肌和上背参与更多。" },
        { label: "脚与躯干", text: "双脚向前放，减少脊柱伸展代偿；身体保持微前倾或接近垂直，不要后仰。" },
        { label: "手肘", text: "肘部保持抬起和轻微内旋，疲劳时也不要让肘掉下去；屈肘多少以个人后束感受为准。" },
        { label: "发力方向", text: "想象手肘向远端延长、再向外展开，不是把肩胛死命夹在一起。" },
        { label: "稳定", text: "动作有压力时先吸满气固定躯干；若肩不舒服，减重并缩小到能稳定完成的水平外展幅度。" },
      ],
    },
    steps: [
      "把座椅调到手肘与肩同高，双脚向前踩稳，躯干微前倾。",
      "保持肘部抬起，用后束让手臂向远端、向外展开，而不是后仰夹背。",
      "后束收紧后受控回程，在肩胛准备前翻或肘部准备下坠前再次展开。",
    ],
    cues: ["手肘与肩同高", "脚往前，躯干微前倾", "向远、向外，不是夹背"],
    mistakes: ["座椅过低导致耸肩", "后仰并用肩胛后缩代偿", "疲劳时肘掉下去、肩内扣"],
    breathing: "展开前吸气稳定躯干；向外展开时呼气，回程保持控制。",
  },
  "shoulder-press": {
    coach: {
      session: "谭成义 · 肩部教学",
      time: "21:14-31:07",
      focus: "腰贴靠背、哑铃略内扣维持肩部张力；下到眼睛附近即可，上端留一点不锁死。",
      points: [
        { label: "靠背", text: "肩部能力好可用较直靠背；腰难以贴住时把靠背稍放低。无论角度如何，先保证腰背稳定。" },
        { label: "手腕", text: "哑铃保持轻微向内扣的意图，让手腕和前臂稳定，不要在下放时松腕、让哑铃向内倒。" },
        { label: "下放", text: "下到手腕约在眼睛高度即可。更深只有在肩部能维持位置且无不适时尝试，不用硬追最低点。" },
        { label: "推起", text: "多数训练者在手臂完全伸直时肩部会松掉，因此顶端留一点距离；能主动保持张力后再逐步增加幅度。" },
        { label: "节奏与起落", text: "下放稍慢但不用极慢，推起可稍快。重哑铃放在膝盖附近，用腿逐只送起，结束时也用腿接回。" },
      ],
    },
    steps: [
      "调好靠背并让腰背贴稳，把哑铃放在膝盖附近，必要时用腿逐只送到起始位。",
      "手腕稳定、哑铃保持轻微内扣意图，向上推到肩部仍有张力的位置。",
      "受控下放到眼睛附近；若肩膀、手腕或腰部开始改变位置，就不要继续加深。",
    ],
    cues: ["腰贴靠背", "手腕稳，哑铃略内扣", "下到眼睛，上端留一点"],
    mistakes: ["拱腰把动作变成上胸推", "下放时松腕内倒", "顶端锁死或底部硬追深度"],
    breathing: "推举前吸气固定躯干；推起时呼气。组内需要换气时先稳住哑铃再补气。",
  },
  "lateral-raise": {
    coach: {
      session: "谭成义 · 肩部教学",
      time: "31:07-34:31",
      focus: "躯干微前倾，手肘带动向前、向外、向上；哑铃碰腿即返，不后仰也不下到底。",
      points: [
        { label: "重心", text: "身体只需轻微前倾，避免重量变大后向后仰；过度前倾也会限制重量和轨迹。" },
        { label: "方向", text: "不是正侧方抬，也不是手先提。让手肘带着手臂向前一点、向外、向上延长。" },
        { label: "高度", text: "在肩部舒服的前提下尽量抬高，以加强三角肌起点收缩；一旦耸肩或不适就降低高度。" },
        { label: "回程", text: "哑铃回到大腿附近便立即再次抬起，不在最底端完全放松，让中束保持连续张力。" },
        { label: "稳定", text: "吸气撑稳胸廓和躯干，手腕保持中立；后仰、甩腰或手先抬都说明重量过大。" },
      ],
    },
    steps: [
      "双脚站稳，躯干轻微前倾，哑铃放在大腿两侧且中束已有张力。",
      "手肘带动手臂向前一点、向外、向上抬，在不耸肩的前提下做到舒适高度。",
      "受控下放到哑铃接近大腿就再次抬起，不在底部完全放松。",
    ],
    cues: ["手肘带动，不是手先提", "向前一点、向外、向上", "碰腿即返，躯干不后仰"],
    mistakes: ["向正侧方甩起", "后仰借腰并耸肩", "底部完全卸力或手腕折弯"],
    breathing: "抬起前吸气稳定躯干；抬起时呼气，下放时保持控制。",
  },
};

Object.entries(COACH_VIDEO_DETAILS).forEach(([id, details]) => {
  Object.assign(GUIDE_BASE[id], details);
});

window.EXERCISE_GUIDES = {
  "assisted-dip": GUIDE_BASE["assisted-dip"],
  "leg-press": GUIDE_BASE["leg-press"],
  "chest-press": GUIDE_BASE["chest-press"],
  "lat-pulldown": GUIDE_BASE["lat-pulldown"],
  "leg-curl": GUIDE_BASE["leg-curl"],
  "seated-row": GUIDE_BASE["seated-row"],
  "lateral-raise": GUIDE_BASE["lateral-raise"],
  crunch: GUIDE_BASE.crunch,
  "cardio-20": GUIDE_BASE.cardio,
  "machine-lateral-raise": GUIDE_BASE["machine-lateral-raise"],
  "reverse-fly": GUIDE_BASE["reverse-fly"],
  "triceps-pushdown": GUIDE_BASE["triceps-pushdown"],
  "biceps-curl": GUIDE_BASE["biceps-curl"],
  "reverse-grip-pulldown": GUIDE_BASE["reverse-grip-pulldown"],
  "narrow-neutral-row": GUIDE_BASE["narrow-neutral-row"],
  "straight-arm-pulldown": GUIDE_BASE["straight-arm-pulldown"],
  "rear-delt-extension": GUIDE_BASE["rear-delt-extension"],
  "leg-extension": GUIDE_BASE["leg-extension"],
  "shoulder-press": GUIDE_BASE["shoulder-press"],
  "low-cable-fly": GUIDE_BASE["low-cable-fly"],
  "overhead-triceps": GUIDE_BASE["overhead-triceps"],
  "upper-back-row": GUIDE_BASE["upper-back-row"],
  "hammer-curl": GUIDE_BASE["hammer-curl"],
  "post-cardio": GUIDE_BASE.cardio,
  "swim-session": GUIDE_BASE["easy-swim"],
  "crunch-plus": GUIDE_BASE.crunch,
  plank: GUIDE_BASE.plank,
  "cardio-30-a": GUIDE_BASE.cardio,
  "hack-squat": GUIDE_BASE["hack-squat"],
  "incline-press": GUIDE_BASE["incline-press"],
  "chest-supported-row": GUIDE_BASE["chest-supported-row"],
  "hip-thrust": GUIDE_BASE["hip-thrust"],
  "neutral-pulldown": GUIDE_BASE["neutral-pulldown"],
  "reverse-fly-b": GUIDE_BASE["reverse-fly"],
  "crunch-b": GUIDE_BASE.crunch,
  "cardio-short-b": GUIDE_BASE.cardio,
  "light-pulldown": GUIDE_BASE["lat-pulldown"],
  "light-row": GUIDE_BASE["seated-row"],
  "light-chest-press": GUIDE_BASE["chest-press"],
  "hip-abduction": GUIDE_BASE["hip-abduction"],
  "calf-raise": GUIDE_BASE["calf-raise"],
  "core-choice": GUIDE_BASE["core-choice"],
  "cardio-30-b": GUIDE_BASE.cardio,
  "easy-swim": GUIDE_BASE["easy-swim"],
  mobility: GUIDE_BASE.mobility,
  "rest-day": GUIDE_BASE["rest-day"],
};
